# Deploy to gh-pages
dist: trusty
language: node_js
node_js:
  - 12
cache: npm

stages:
  - deploy

before_script:
  - yarn install 
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN #https://docs.travis-ci.com/user/deployment/pages/
  keep-history: true
  target-branch: gh-pages
  local-dir: build
  on:
    branch:
      - master
