# Deploy to gh-pages
dist: trusty
language: node_js
node_js:
  - 10

stages:
  - deploy

before_script:
  # - npm install
  - npm install -g gulp-cli
  - npm run-script build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN #https://docs.travis-ci.com/user/deployment/pages/
  keep-history: true
  target-branch: gh-pages
  local-dir: build
  cache:
    paths:
      - node_modules
  on:
    branch:
      - master
